"""add step_id to materials table

Revision ID: 1c22758d7640
Revises: 46d9c0292344
Create Date: 2025-04-11 18:51:16.589374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c22758d7640'
down_revision: Union[str, None] = '46d9c0292344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'materials', 'steps', ['step_id'], ['id'])
    op.drop_column('materials', 'stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'step_id')
    # ### end Alembic commands ###
