"""add fields to materials

Revision ID: 679584452200
Revises: bb47e8247ee1
Create Date: 2025-04-10 20:03:00.632857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679584452200'
down_revision: Union[str, None] = 'bb47e8247ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('type', sa.String(), nullable=True))
    op.add_column('materials', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('materials', sa.Column('serial', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'materials', ['serial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='unique')
    op.drop_column('materials', 'serial')
    op.drop_column('materials', 'expiration_date')
    op.drop_column('materials', 'type')
    # ### end Alembic commands ###
